services:
  db:
    image: postgres:alpine3.22 # Using a recent Alpine-based PostgreSQL image
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: nano_clients
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data using a named volume
    restart: always # Ensure the container restarts if it stops

volumes:
  db_data: # Define the named volume